server:
  port: 8080
spring:
  application:
    name: ms-ancient-artifacts
  webflux:
    base-path: /
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:h2:mem:///artifacts
    username: admin
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
    initialization-mode: always

logging:
  level:
    root: INFO

management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
      cache:
        time-to-live: 10s
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
        liveness: liveness
        readiness: readiness
      exposure:
        include: health, liveness, readiness, metrics