server:
  port: 8080
spring:
  application:
    name: ms-ancient-artifacts
  webflux:
    base-path: /
  devtools:
    add-properties: false

logging:
  level:
    root: INFO

management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
      cache:
        time-to-live: 10s
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
        liveness: liveness
        readiness: readiness
      exposure:
        include: health, liveness, readiness, metrics